ScrumTableApp.MvcWebUI/Models/Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScrumTableApp.MvcWebUI.Models
{
  public class Model
  {
    public string Name { get; set; }

  }
}

ScrumTableApp.MvcWebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ScrumTableApp.Data.Abstract;
using ScrumTableApp.Entity;
using ScrumTableApp.MvcWebUI.Models;

namespace ScrumTableApp.MvcWebUI.Controllers
{
  public class HomeController : Controller
  {
    private ITaskRepository taskRepository;
    private IStoryRepository storyRepository;

    public HomeController(ITaskRepository trepository,IStoryRepository srepository)
    {
      taskRepository = trepository;
      storyRepository = srepository;
    }
    public IActionResult Index()
    {
      
      return View();
    }


    [HttpPost]
    public IActionResult CreateStory(Story entity)
    {

      storyRepository.AddStory(entity);

      return RedirectToAction("Index");
    }
    [HttpPost]
    public IActionResult CreateTask(Entity.Task entity)
    {
      entity.Durum = 1;
      taskRepository.AddTask(entity);
      return RedirectToAction("Index");
    }
    [HttpPost]
    public IActionResult DurumDegis(int id,int durum)
    {
      int yeniDurum=1;
      if (durum == 1)
      {
        yeniDurum = 2;
      }else if (durum == 2)
      {
        yeniDurum = 3;
      }
      var entity = new Entity.Task();
      entity = taskRepository.GetById(id);
      entity.Durum = yeniDurum;
      taskRepository.updateTask(entity);

      return RedirectToAction("Index");

    }
    [HttpPost]
    public IActionResult TaskDelete(int id)
    {
      taskRepository.DeleteTask(id);

      return RedirectToAction("Index");
    }
  }
}

ScrumTableApp.MvcWebUI/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScrumTableApp.MvcWebUI.ViewComponents
{
  public class MenuViewComponent : ViewComponent
  {
    public IViewComponentResult Invoke()
    {
      return View();
    }
  }
}

ScrumTableApp.MvcWebUI/ViewComponents/TableViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ScrumTableApp.Data.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScrumTableApp.MvcWebUI.ViewComponents
{
  public class TableViewComponent : ViewComponent
  {
    private IStoryRepository storyRepository;
    private ITaskRepository taskRepository;

    public TableViewComponent(ITaskRepository trepository, IStoryRepository srepository)
    {
      storyRepository = srepository;
      taskRepository = trepository;
    }
    public IViewComponentResult Invoke()
    {
      ViewBag.Tasks = taskRepository.GetAll();
      return View(storyRepository.GetAll());

    }
  }
}

ScrumTableApp.MvcWebUI/ViewComponents/TaskViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ScrumTableApp.Data.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScrumTableApp.MvcWebUI.ViewComponents
{
  public class TaskViewComponent : ViewComponent
  {
    private IStoryRepository storyRepository;

    public TaskViewComponent(ITaskRepository trepository, IStoryRepository srepository)
    {
      storyRepository = srepository;
    }
    public IViewComponentResult Invoke()
    {
      ViewBag.Stories = new SelectList(storyRepository.GetAll(), "StoryId", "Name");
      return View();
    }
  }
}

ScrumTableApp.MvcWebUI/Views/Home/Index.cshtml
@{
  ViewData["Title"] = "Index";
}

<div class="row">

  @await Component.InvokeAsync("Menu")

  @await Component.InvokeAsync("Task")
  
  @await Component.InvokeAsync("Table");

</div>

ScrumTableApp.MvcWebUI/Views/Shared/Components/Menu/Default.cshtml
@model Story

<div class="col-md-12">
  <h3 class="text-center">Add Story</h3>
  <form method="post" asp-controller="Home" asp-action="CreateStory">
    <div class="form-group">
      <label asp-for="Name">Story Name</label>
      <input asp-for="Name" class="form-control" id="formGroupExampleInput" placeholder="Story Name">
    </div>
    <div class="form-group">
      <label asp-for="Description">Story Description</label>
      <input asp-for="Description" class="form-control" id="formGroupExampleInput" placeholder="Story Description">
    </div>
    <input class="btn btn-success" type="submit" value="Create" />
  </form>
</div>

ScrumTableApp.MvcWebUI/Views/Shared/Components/Table/Default.cshtml
@model IEnumerable<Story>

<table class="table table-hover mt-4">
  <thead>
    <tr>
      <th scope="col">Stories</th>
      <th scope="col">To Do</th>
      <th scope="col">In Progress</th>
      <th scope="col">Done</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model)
    {

      <tr>
        <td>
          <div class="storyBox">
            <h4>@item.Name</h4>
            <p>@item.Description</p>

          </div>
        </td>



        <td>

          @foreach (var item1 in ViewBag.Tasks)
          {

            @if (item1.StoryId == item.StoryId && item1.Durum == 1)
            {

              <div class="taskBox">

                <h4>@item1.Name</h4>
                <p>@item1.Description</p>
                <form asp-action="durumDegis" asp-controller="Home" method="post">
                  <input type="hidden" name="id" value="@item1.TaskId" />
                  <input type="hidden" name="durum" value="@item1.Durum" />
                  <input class="btn btn-warning mt-2" type="submit" value="Yana Geç" />

                </form>
              </div>



            }


          }

        </td>
        <td>

          @foreach (var item1 in ViewBag.Tasks)
          {

            @if (item1.StoryId == item.StoryId && item1.Durum == 2)
            {

              <div class="taskBox">
                <h4>@item1.Name</h4>
                <p>@item1.Description</p>

                <form asp-action="durumDegis" asp-controller="Home" method="post">
                  <input type="hidden" name="id" value="@item1.TaskId" />
                  <input type="hidden" name="durum" value="@item1.Durum" />
                  <input class="btn btn-warning mt-2" type="submit" value="Yana Geç" />

                </form>
              </div>



            }


          }

        </td>
        <td>

          @foreach (var item1 in ViewBag.Tasks)
          {

            @if (item1.StoryId == item.StoryId && item1.Durum == 3)
            {

              <div class="taskBox">

                <h4>@item1.Name</h4>
                <p>@item1.Description</p>

                <form asp-action="TaskDelete" asp-controller="Home" method="post">
                  <input type="hidden" name="id" value="@item1.TaskId" />
                  <input class="btn btn-danger mt-2" type="submit" value="Taskı Sil" />

                </form>
              </div>



            }


          }

        </td>
      </tr>

    }




  </tbody>
</table>

ScrumTableApp.MvcWebUI/Views/Shared/Components/Task/Default.cshtml
@model ScrumTableApp.Entity.Task

<div class="col-md-12">
  <h3 class="text-center">Add Task</h3>
  <form method="post" asp-controller="Home" asp-action="CreateTask">
    <div class="form-group">
      <label asp-for="Name">Task Name</label>
      <input asp-for="Name" class="form-control" id="formGroupExampleInput" placeholder="Task Name">
    </div>
    <div class="form-group">
      <label asp-for="Description">Task Description</label>
      <input asp-for="Description" class="form-control" id="formGroupExampleInput" placeholder="Task Description">
    </div>
    <div class="form-group">
      <label asp-for="StoryId"></label>
      <select class="form-control" asp-for="StoryId" asp-items="ViewBag.Stories">
      </select>
    </div>
    <input class="btn btn-success" type="submit" value="Create" />
  </form>
</div>

ScrumTableApp.MvcWebUI/Views/Shared/_Layout.cshtml
@{
  Layout = null;
}

<!DOCTYPE html>

<html>
<head>
  <meta name="viewport" content="width=device-width" />
  <title>Scrum Table</title>

  <link href="~/css/bundle.min.css" rel="stylesheet" />
</head>
<body>

  <div class="container">
    <div class="row">

      <div class="col-md-12 text-center text-warning"><h2 class="title">Scrum Table</h2></div>

    </div>
    @RenderBody()

  </div>
 


  <script src="~/js/bundle.js"></script>
</body>
</html>